[tool.flake8]
ignore = ["E722"]  # Ignore broad exception warnings

[tool.pylint."MESSAGES CONTROL"]
disable = ["broad-except"]  # Disable broad exception warnings

[tool.ruff]
ignore = ["E722"]  # Ignore broad exception warnings

[tool.pycodestyle]
ignore = ["E722"]  # Ignore broad exception warnings

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"  # Set default fixture loop scope 